### ISSUE TITLE
java.lang.VerifyError: SingleControl_Proxy

### ISSUE THREAD

**Issue by sfsheng0322** [crittercism/dexmaker#28]
java.lang.VerifyError: SingleControl_Proxy
	at java.lang.reflect.Field.setField(Native Method)
	at java.lang.reflect.Field.set(Field.java:585)
	at com.google.dexmaker.stock.ProxyBuilder.setMethodsStaticField(ProxyBuilder.java:299)
	at com.google.dexmaker.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:269)
	at com.google.dexmaker.stock.ProxyBuilder.build(ProxyBuilder.java:205)

Can you help me to find why?

**Comment by reutann** [comment]
+1, I'm seeing this too.
